name: service prod deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-back:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Login to Cloud Container Registry
        run: echo "${{ secrets.CLOUDRU_PASS }}" | docker login sigmamales.cr.cloud.ru -u ${{ secrets.CLOUDRU_USER }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            sigmamales.cr.cloud.ru/networkator:${{ github.sha }}-${{ env.PLATFORM_PAIR }}
            sigmamales.cr.cloud.ru/networkator:latest-${{ env.PLATFORM_PAIR }}
