name: service prod deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: docker_buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Cloud Container Registry
        run: echo "${{ secrets.CLOUDRU_PASS }}" | docker login sigmamales.cr.cloud.ru -u ${{ secrets.CLOUDRU_USER }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            sigmamales.cr.cloud.ru/networkator:${{ github.sha }}
            sigmamales.cr.cloud.ru/networkator:latest